### ISSUE TITLE
Return apps display name

### ISSUE THREAD

**Issue by marcosmartini** [jstokes/rn-installed-apps#4]
I wonder how to return also the apps display names and icons.

**Comment by jstokes** [comment]
This information may be accessible through the `PackageInfo`s `ApplicationInfo` - have a look at what is available here: https://android.googlesource.com/platform/frameworks/base/+/e639da7/core/java/android/content/pm/ApplicationInfo.java

We're getting the `ApplicationInfo` already for `getNonSystemApps` to look at system flags.
